-- Creacion tabla rol

CREATE TABLE ROL
(
ID_ROL NUMBER(10), 
NOMBRE_ROL VARCHAR2(80)
);

-- Se define la llave primaria

ALTER TABLE ROL ADD
CONSTRAINT PK_ROL PRIMARY KEY(ID_ROL);


-- inserción de registros

INSERT INTO ROL (ID_ROL,NOMBRE_ROL) VALUES (1,'ADMINISTRADOR');
INSERT INTO ROL (ID_ROL,NOMBRE_ROL) VALUES (2,'AUDITOR');
INSERT INTO ROL (ID_ROL,NOMBRE_ROL) VALUES (3,'AUXILIAR');


-- Creación tabla usuario


CREATE TABLE USUARIO 
(
ID_USUARIO NUMBER(10),
ID_ROL NUMBER(10),
NOMBRE_USU VARCHAR2(80),
ACTIVO CHAR(2)
);


-- se define llave primaria

ALTER TABLE USUARIO ADD (
  CONSTRAINT PK_USU PRIMARY KEY (ID_USUARIO));

-- se define llave foranea  
  
ALTER TABLE USUARIO ADD (
  CONSTRAINT FK_USU
  FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL));
  
-- se crea secuencia para el incremento, iniciando desde 1  

CREATE SEQUENCE ID_SEQ 
START WITH 1 
INCREMENT BY 1;


-- se crea pl para la realización del conteo

CREATE OR REPLACE TRIGGER ID_BIR 
BEFORE INSERT ON USUARIO 
FOR EACH ROW

BEGIN
  SELECT ID_SEQ.NEXTVAL
  INTO   :NEW.ID_USUARIO
  FROM   DUAL;
END;

